import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthProvider from '@/lib/auth/Provider'
import TrpcProvider from '@/lib/trpc/Provider'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/ui/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(inter.className, 'max-h-full h-full max-w-full w-full')}
      >
        <NextAuthProvider>
          <TrpcProvider>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
              <main className='p-8 w-screen h-full'>{children}</main>
            </ThemeProvider>
          </TrpcProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
